resources: "config/resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.0.1"

trimmer_software: "fastp"

reference:
  background: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/PoN/hydra_test/background_panel.tsv"
  artifacts: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/PoN/hydra_test/artifact_panel.txt"
  fasta: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fasta"
  dict: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.dict"
  fna: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fna"
  amb: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.amb"
  ann: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.ann"
  bwt: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.bwt"
  fai: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fai"
  pac: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.pac"
  sa: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.sa"
  design_bed: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/pool1_pool2_nochr_3c.sort.merged.padded20.hg19.210311.met.annotated.bed"
  skip_chrs:
    - "chrM"


bwa_mem:
  container: "docker://hydragenetics/bwa_mem:0.7.17"
  extra: "-R '@RG\\tID:{sample}\\tSM:{sample}\\tPL:illumina\\tPU:{sample}' -v 1 "

mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.0"

samtools_index:
  container: "docker://hydragenetics/common:0.0.1"

merge_bam:
  container: "docker://hydragenetics/common:0.0.1"

fastp_pe:
  container: "docker://hydragenetics/fastp:0.20.1"

vardict:
  container: "docker://gmsuppsala/somatic:develop"
  bed_columns: "-c 1 -S 2 -E 3 -g 4"
  allele_frequency_threshold: "0.01"

mutect2:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

mutect2_gvcf:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

merge_vcf:
  container: "docker://gmsuppsala/somatic:develop"

merge_gvcf:
  container: "docker://gmsuppsala/somatic:develop"

bgzip_vcf:
  container: "docker://gmsuppsala/somatic:develop"

tabix_vcf:
  container: "docker://gmsuppsala/somatic:develop"

decompose:
  container: "docker://gmsuppsala/somatic:develop"

normalize:
  container: "docker://gmsuppsala/somatic:develop"

sort_vcf:
  container: "docker://gmsuppsala/somatic:develop"

ensemble_vcf:
  container: "docker://gmsuppsala/somatic:develop"
  callers:
    - vardict
    - mutect2
  sort_order: "vardict,mutect2"

fix_af:
  container: "docker://gmsuppsala/somatic:develop"

freebayes:
  container: "docker://gmsuppsala/somatic:develop"

vep:
  container: "docker://ensemblorg/ensembl-vep:release_99.0"
  vep_cache:  VEP/homo_sapiens
  mode: "--database"
  extra: " --af  "

calculate_seqrun_background:
  container: "docker://python:3.9.7-slim"

bgzip_vcf:
  container: "docker://gmsuppsala/somatic:develop"

tabix_vcf:
  container: "docker://gmsuppsala/somatic:develop"
