default_resources:
  threads: 1
  time: "4:00:00"
  mem_mb: 1024
  mem_per_cpu: 3072
  partition: low

bwa_mem:
  threads: 10
  time: "8:00:00"

fastp_pe:
  threads: 5

vep:
  threads: 10

fastqc:
  threads: 10

mutect2_gvcf:
  threads: 4
  time: "8:00:00"
  mem_mb: 8192

mutect2:
  threads: 4
  time: "8:00:00"
  mem_mb: 8192

gene_fuse:
  threads: 4

cnvkit_call:
  threads: 8
